### ISSUE TITLE
LOCAL ISSUE Disregard, LevelDB getting stuck In Amulet on last stage.

### ISSUE THREAD

**Issue by PREMIEREHELL** [Amulet-Team/Amulet-LevelDB#9]
[test.zip](https://github.com/Amulet-Team/Amulet-LevelDB/files/10178537/test.zip)
This world has all but 4 chunks removed but has not been compacted
Open and close Twice within Amulet but don't close the app.
You can't delete the file "000977.ldb"
If .compact() is run isolated this file gets removed and the other gets renamed. 

Also Note: this is with The latest LevelDB compiled. The Dead Lock Patch.

You don't even need to load the 3d Editor to test.
if you close the amulet and reopen the world its fixed
![Capture](https://user-images.githubusercontent.com/88470674/206253623-f20d402e-3a0b-448d-92bf-f4f03f34af61.PNG)

**Comment by gentlegiantJGC** [comment]
If this is not an issue, please close it.
